export const initialEdges = [
  {
    type: "Padrao",
    source: "2",
    sourceHandle: null,
    target: "1",
    targetHandle: null,
    id: "reactflow__edge-2-1",
  },
  {
    type: "Padrao",
    source: "3",
    sourceHandle: null,
    target: "2",
    targetHandle: null,
    id: "reactflow__edge-3-2",
  },
  {
    type: "Padrao",
    source: "4",
    sourceHandle: null,
    target: "3",
    targetHandle: null,
    id: "reactflow__edge-4-3",
  },
  {
    type: "Padrao",
    source: "5",
    sourceHandle: null,
    target: "4",
    targetHandle: null,
    id: "reactflow__edge-5-4",
  },
  {
    type: "Padrao",
    source: "6",
    sourceHandle: null,
    target: "7",
    targetHandle: null,
    id: "reactflow__edge-6-7",
  },
  {
    type: "Padrao",
    source: "7",
    sourceHandle: null,
    target: "5",
    targetHandle: null,
    id: "reactflow__edge-7-5",
  },
];
