export const initialEdges = [
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "2",
    sourceHandle: null,
    target: "1",
    targetHandle: null,
    id: "reactflow__edge-2-1",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "3",
    sourceHandle: null,
    target: "2",
    targetHandle: null,
    id: "reactflow__edge-3-2",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "5",
    sourceHandle: null,
    target: "2",
    targetHandle: null,
    id: "reactflow__edge-5-2",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "6",
    sourceHandle: null,
    target: "2",
    targetHandle: null,
    id: "reactflow__edge-6-2",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "4",
    sourceHandle: null,
    target: "3",
    targetHandle: null,
    id: "reactflow__edge-4-3",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "7",
    sourceHandle: null,
    target: "5",
    targetHandle: null,
    id: "reactflow__edge-7-5",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "8",
    sourceHandle: null,
    target: "6",
    targetHandle: null,
    id: "reactflow__edge-8-6",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "9",
    sourceHandle: null,
    target: "8",
    targetHandle: null,
    id: "reactflow__edge-9-8",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "10",
    sourceHandle: null,
    target: "8",
    targetHandle: null,
    id: "reactflow__edge-10-8",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "12",
    sourceHandle: null,
    target: "9",
    targetHandle: null,
    id: "reactflow__edge-12-9",
  },
  {
    type: "Padrao",
    markerStart: {
      type: "arrowclosed",
      width: 30,
      height: 30,
      color: "#8d8d8d",
    },
    source: "11",
    sourceHandle: null,
    target: "10",
    targetHandle: null,
    id: "reactflow__edge-11-10",
  },
];
